// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongKham.Models.Data;

#nullable disable

namespace QuanLyPhongKham.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DANHMUCTHUOCDONTHUOC", b =>
                {
                    b.Property<Guid>("DanhMucThuocsMaThuoc")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DonThuocsMaDT")
                        .HasColumnType("char(36)");

                    b.HasKey("DanhMucThuocsMaThuoc", "DonThuocsMaDT");

                    b.HasIndex("DonThuocsMaDT");

                    b.ToTable("DANHMUCTHUOCDONTHUOC");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.BACSI", b =>
                {
                    b.Property<Guid>("MaBS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChuyenKhoa")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaTK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.HasKey("MaBS");

                    b.HasIndex("MaTK");

                    b.ToTable("BacSis");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.BENHNHAN", b =>
                {
                    b.Property<Guid>("MaBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoBHYT")
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.Property<string>("TienSuDiUng")
                        .HasColumnType("longtext");

                    b.HasKey("MaBN");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.DANHMUCDICVU", b =>
                {
                    b.Property<Guid>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaDV");

                    b.ToTable("DanhMucDichVus");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.DANHMUCTHUOC", b =>
                {
                    b.Property<Guid>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChongChiDinh")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThuoc");

                    b.ToTable("DanhMucThuocs");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.DONTHUOC", b =>
                {
                    b.Property<Guid>("MaDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MaPK")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKe")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaDT");

                    b.HasIndex("MaPK");

                    b.ToTable("DonThuocs");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.HOADON", b =>
                {
                    b.Property<Guid>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaLeTan")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MaPK")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasColumnType("longtext");

                    b.HasKey("MaHD");

                    b.HasIndex("MaPK")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.LICHHEN", b =>
                {
                    b.Property<Guid>("MaLH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MaBN")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MaBS")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ThoiGianKham")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLH");

                    b.HasIndex("MaBN");

                    b.HasIndex("MaBS");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.LICHLAMVIEC", b =>
                {
                    b.Property<Guid>("MaLLV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MaBS")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaLLV");

                    b.HasIndex("MaBS");

                    b.ToTable("LichLamViecs");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.NHANVIEN", b =>
                {
                    b.Property<Guid>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.HasKey("MaNV");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.PHIEUKHAM", b =>
                {
                    b.Property<Guid>("MaPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChuanDoan")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HuongDieuTri")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MaBS")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MaLH")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThaiTiepNhan")
                        .HasColumnType("longtext");

                    b.Property<string>("TrieuChung")
                        .HasColumnType("longtext");

                    b.HasKey("MaPK");

                    b.HasIndex("MaBS");

                    b.HasIndex("MaLH")
                        .IsUnique();

                    b.ToTable("PhieuKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.RefreshTokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokenModels");
                });

            modelBuilder.Entity("DANHMUCTHUOCDONTHUOC", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.DANHMUCTHUOC", null)
                        .WithMany()
                        .HasForeignKey("DanhMucThuocsMaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham.Models.Entities.DONTHUOC", null)
                        .WithMany()
                        .HasForeignKey("DonThuocsMaDT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.BACSI", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.DONTHUOC", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.PHIEUKHAM", "PhieuKham")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaPK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.HOADON", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.PHIEUKHAM", "PhieuKham")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyPhongKham.Models.Entities.HOADON", "MaPK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.LICHHEN", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.BENHNHAN", "BenhNhan")
                        .WithMany("LichHen")
                        .HasForeignKey("MaBN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyPhongKham.Models.Entities.BACSI", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBS")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.LICHLAMVIEC", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.BACSI", "BacSi")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaBS")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.PHIEUKHAM", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.Entities.BACSI", "BacSi")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("MaBS")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyPhongKham.Models.Entities.LICHHEN", "LichHen")
                        .WithOne("PhieuKham")
                        .HasForeignKey("QuanLyPhongKham.Models.Entities.PHIEUKHAM", "MaLH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSi");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.BACSI", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("LichLamViecs");

                    b.Navigation("PhieuKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.BENHNHAN", b =>
                {
                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.LICHHEN", b =>
                {
                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Entities.PHIEUKHAM", b =>
                {
                    b.Navigation("DonThuocs");

                    b.Navigation("HoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
